name: Auto-merge dependabot updates

on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          use-github-auto-merge: true
